services: 
    api_db:
      
      container_name: api_db
      image: postgres:18.3-alpine3.23
      volumes:
        -  ./tabelas/sql.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        POSTGRES_PASSWORD: 123
      ports:
        - 5433:5432
    api: 
      build: .
      container_name: api
      
      #image: api
      ports:
        - 8080:8080
      env_file: Api/.env
      



